FROM node:22-alpine AS builder
USER 0
WORKDIR /opt/app-root/src
COPY package.json package-lock.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM registry.access.redhat.com/ubi9/nginx-124:1
COPY --from=builder /opt/app-root/src/build/ /opt/app-root/src/
COPY nginx/nginx.conf "${NGINX_CONF_PATH}"
EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]
