apiVersion: v2
name: migration-toolkit-rhcl
description: 3scale to Red Hat Connectivity Link migration toolkit
type: application
version: 1.0.0
appVersion: "1.0.0"
home: https://github.com/Everything-is-Code/migration-toolkit-rhcl
sources:
  - https://github.com/Everything-is-Code/migration-toolkit-rhcl
maintainers:
  - name: Everything-is-Code
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/operator: "false"
  artifacthub.io/images: |
    - name: backend
      image: quay.io/everythingascode/migration-toolkit-rhcl-backend:v0.1.0
      whitelisted: true
    - name: frontend
      image: quay.io/everythingascode/migration-toolkit-rhcl-frontend:v0.1.0
      whitelisted: true
    - name: postgresql
      image: registry.redhat.io/rhel9/postgresql-15@sha256:df15212ae9cc010ebe9dd61b19332a845c8b7df3dd00fb70e47d6e925f8b75e7
      whitelisted: true
