apiVersion: v1
kind: Service
metadata:
  name: {{ include "migration-toolkit-rhcl.frontend" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "migration-toolkit-rhcl.frontend" . }}
    app.kubernetes.io/component: frontend
    {{- include "migration-toolkit-rhcl.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: {{ include "migration-toolkit-rhcl.frontend" . }}
