apiVersion: v1
kind: Secret
metadata:
  name: {{ include "migration-toolkit-rhcl.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "migration-toolkit-rhcl.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_USER: {{ .Values.postgresql.username | quote }}
  DB_PASSWORD: {{ .Values.postgresql.password | quote }}
  DB_NAME: {{ .Values.postgresql.database | quote }}
