apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "migration-toolkit-rhcl.backend" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "migration-toolkit-rhcl.labels" . | nindent 4 }}
{{- with .Values.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
